### ISSUE TITLE
reverse complement

### ISSUE THREAD

**Issue by jazberna1** [marcelm/dnaio#64]
Dear dnaio team,

is there a method to get reverse complement?

Thanks
Jorge

**Comment by rhpvorderman** [comment]
It is python builtin:
```python
from dnaio import Sequence

complement_table = str.maketrans(dict(A="T", C="G", G="C", T="A"))
my_sequence = Sequence("my_seq", "GATTACA", "HHHHHHH")
my_sequence.sequence.translate(complement_table)
```

Results in `'CTAATGT'`

Does this work for you?

**Comment by marcelm** [comment]
Reverse complements aren’t hard, but there are things one can get wrong, so it’s worth having a method for it. I would definitely not call it "built in". Note that a proper function should also work for wildcards and lowercase characters (and the example you gave is missing the "reversing" part.)

Here is what I use in Cutadapt:
https://github.com/marcelm/cutadapt/blob/26d3f39b6a37bcee8383d7d8f4a95879528137e4/src/cutadapt/utils.py#L172-L189

I wouldn’t mind moving this to dnaio. Just as we have methods for slicing a SequenceRecord, computing a reverse complement is also a thing one regularly needs to do with DNA sequences, so it’s IMO natural to offer this.

**Comment by rhpvorderman** [comment]
I agree. I wanted to offer a quick fix that could be used now, and then failed to answer the original question. Sorry.

> Note that a proper function should also work for wildcards and lowercase characters (and the example you gave is missing the "reversing" part.)

And then gave a bad answer too by not reversing... It's not a great day today.

> I wouldn’t mind moving this to dnaio. Just as we have methods for slicing a SequenceRecord, computing a reverse complement is also a thing one regularly needs to do with DNA sequences, so it’s IMO natural to offer this.

I see cutadapt uses a translate table then reverses using Python. This is fast enough, but there are two caveats
- Python uses a dict to translate, because there are so many unicode code points. Since we guarantee 1-byte kind strings we can use a 256 character table. (bytes.maketrans automatically creates one of these as well). 
- We can do the reversing and translation at the same time. Creating a new unicode object and then populating it with the translated nucleotides in reverse.

When we do that in Cython it should be quite a bit faster than the python method so this should also be a win for cutadapt.

SequenceRecord and BytesSequenceRecord can share the underlying method easily I think. Just as with the is_mate function.

**Comment by marcelm** [comment]
Oh great, it sounded as if you were opposed to adding the functionality. And I’m of course all for speeding things up!

**Comment by rhpvorderman** [comment]
> Thanks so much for the comments. I'll have a go with str.maketrans and translate

And for the reverse part there is a built-in reversed function: https://docs.python.org/3/library/functions.html#reversed . Good luck!

In the meantime we may hammer out a method, but I can give no ETA at this point. My time is rather limited now.
