### ISSUE TITLE
Does SequenceRecord need to support the buffer protocol?

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/dnaio#76]
The buffer protocol is basically a pointer to a struct that contains two function pointers. One function to acquire the buffer and one to release it. Simple buffers only have a buffer acquire function. This function increases the reference count of the object and uses the internal data pointer of the object. Since python automatically decreases the reference of the buffer exporting object on release, an external release function is not required. This is what is used for bytes objects. More complex buffer objects do some extra work, like setting a lock value to an object, to ensure it can't be changed while exporting a buffer.  

Why support this for SequenceRecord? Well, because it is possible to write a FASTQ record to a block of memory, expose this as the buffer and then free the memory afterwards again. This basically adds a `__bytes__` method to SequenceRecord. It also allows for SequenceRecord objects to be written directly to a Python file, without usage of the `fastq_bytes` method. This shaves off a little overhead.

I faced the same choice when programming the BamRecord object for htspy, and decided not to do it (yet) because I feel a `to_bytes` method is more intuitive and a new buffer needs to be created anyway. So it is best to communicate this to users even if this has a minor performance penalty (method lookup). Nevertheless I am curious about your opinion on this.

**Comment by marcelm** [comment]
So do I understand correctly that the advantage be that you could replace this:
```
with open("out.fastq", "wb") as f:
    f.write(record.to_bytes())
```
with this?
```
with open("out.fastq", "wb") as f:
    f.write(record)
```

> This basically adds a `__bytes__` method to SequenceRecord.

Hm, that confused me. The way I interpret it, [`__bytes__`](https://docs.python.org/3/reference/datamodel.html?highlight=__bytes__#object.__bytes__) doesn’t have anything to do with the buffer protocol and is only used by `bytes()`. So implementing that allows you to write `bytes(record)` instead of `record.fastq_bytes()`.

> because I feel a `to_bytes` method is more intuitive and a new buffer needs to be created anyway

I think so, too. I would prefer to be explicit about the conversion to bytes. Also, I cannot shake the feeling that this isn’t quite how the buffer protocol is intended to be used. The [buffer protocol docs](https://docs.python.org/3/c-api/buffer.html?highlight=buffer%20protocol#buffer-structure) say that "[buffers] could be used to pass around structured data in its native, in-memory format" so this also seems to be a use case, but FASTQ format isn’t actually the internal representation in our case, it just happens to be a way to format the data. We even have another way of formatting (with `two_headers=True`), which wouldn’t be supported with the buffer protocol and requires a method call anyway.

**Comment by rhpvorderman** [comment]
> Hm, that confused me. The way I interpret it, [__bytes__](https://docs.python.org/3/reference/datamodel.html?highlight=__bytes__#object.__bytes__) doesn’t have anything to do with the buffer protocol and is only used by bytes(). So implementing that allows you to write bytes(record) instead of record.fastq_bytes().

Yes that is correct. I meant to say that adding a buffer protocol also makes `bytes(record)` work. 

>  Also, I cannot shake the feeling that this isn’t quite how the buffer protocol is intended to be used.

This is why I did not end up using it for BamRecord as well. It feels a bit odd. 

> but FASTQ format isn’t actually the internal representation in our case, it just happens to be a way to format the data.

We could do that too, it would make reading and writing a lot faster. On the other hand it would make actually using the object by accessing/changing the members a lot slower. In the end it would just be shooting ourselves in the foot for the sake of benchmarks.

Actually htslib does exactly this. It saves all of the BamRecord as is in memory, and stores the offsets internally. This is advantages as accessing memory by offset has zero overhead in C. It is a bit less fortunate for manipulation of the record though. But I think htslib assumes correctly that it will be used mostly for reading. For dnaio we know that assumption is not true.
