### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by stheil15** [marcelm/dnaio#83]
Hi,
I am a long time user of cutadapt.
I've tried to update recently but i encounter this error while installing dnaio.

```
building 'dnaio._core' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUSE_SSE2 -I/usr/include/python3.8 -c src/dnaio/_core.c -o build/temp.linux-x86_64-cpython-38/src/dnaio/_core.o
x86_64-linux-gnu-gcc: error: src/dnaio/_core.c: Aucun fichier ou dossier de ce type
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```
Can't figure out why _core.c is missing.

**Comment by marcelm** [comment]
Which Python version and operating system is this? Which command did you run that gave you the above error?

**Comment by marcelm** [comment]
In recent dnaio versions, we do not ship the `_core.c` file anymore. It should be generated automatically at installation time from the `_core.pyx` file. Strange that this does not appear to happen here. We do need to know more about the system in order to help.

**Comment by marcelm** [comment]
In recent dnaio versions, we do not ship the `_core.c` file anymore. It is generated automatically at installation time from the `_core.pyx` file.

Which Python version are you using and which command(s) did you run that gave you the above error message?

Also, when using `pip install` on a supported Python version, no compilation should actually happen anyway (because pre-compiled wheel files are used).

**Comment by marcelm** [comment]
Oh yes, that is definitely a too old pip version, great you figured it out yourself.
